### AUTH ###
###
POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
  "name": "David",
  "email": "david@example.com",
  "password": "!Pass678",
  "password_confirmation": "!Pass678"
}

###
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "email": "david@example.com",
  "password": "!Pass678"
}

###
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin@78"
}

###
POST http://127.0.0.1:8000/api/logout
Authorization: Bearer access_token

###
GET http://127.0.0.1:8000/api/me
Authorization: Bearer access_token

### CATEGORIES ###
###
POST http://127.0.0.1:8000/api/categories
Authorization: Bearer access_token
Content-Type: application/json

{
  "name": "New Category"
}

###
PUT http://127.0.0.1:8000/api/categories/1
Authorization: Bearer access_token
Content-Type: application/json

{
  "name": "New Category Updated"
}

###
DELETE http://127.0.0.1:8000/api/categories/11
Authorization: Bearer access_token

###
GET http://127.0.0.1:8000/api/categories

###
GET http://127.0.0.1:8000/api/categories/1

### PRODUCTS ###
###
POST http://127.0.0.1:8000/api/products
Authorization: Bearer access_token
Content-Type: application/json

{
  "name": "New Product",
  "description": "Product description",
  "price": 99.99,
  "category_id": 1,
  "colors": {
    "Red": "#FF0000",
    "Blue": "#0000FF"
  }
}

###
PUT http://127.0.0.1:8000/api/products/product_uuid
Authorization: Bearer access_token
Content-Type: application/json

{
  "name": "Updated Product",
  "description": "Updated description",
  "price": 79.99,
  "category_id": 1,
  "colors": {
    "Green": "#00FF00",
    "Blue": "#0000FF"
  }
}

###
DELETE http://127.0.0.1:8000/api/products/product_uuid
Authorization: Bearer access_token

###
GET http://127.0.0.1:8000/api/products

###
GET http://127.0.0.1:8000/api/products/product_uuid